# Description: Configuration file for the trading simulation

tickers: ["AAPL", "MSFT", "GOOG", "TSLA"]
start: "2020-01-01"
end: "2024-12-31"
slippage: 0.001
commission: 0.0005
strategies:
  mean_reversion:
    class: MeanReversionStrategy
    allocator: VolatilityScaledAllocator
    weight: 0.6
    strategy_kwargs:
      lookback: 20
      bound: 2
  momentum:
    class: MomentumStrategy
    allocator: VolatilityScaledAllocator
    weight: 0.4
    strategy_kwargs:
      lookback: 20
benchmark:
  class: BuyAndHoldStrategy
  allocator: EqualWeightAllocator
  ticker: SPY
