[theme]
primaryColor = "#004E89"       # Deep blue for highlights
backgroundColor = "#F8F9FA"    # Soft light gray
secondaryBackgroundColor = "#FFFFFF"  # Clean white for cards/panels
textColor = "#212529"          # Near-black for legibility
font = "sans serif"
