[theme]
base = "light"
primaryColor = "#207f73"             # Teal (from earlier)
backgroundColor = "#f5f2f1"          # Soft off-white background from your image
secondaryBackgroundColor = "#e6ebe9" # Slightly darker for cards/panels
textColor = "#1a1a1a"                # Dark readable text