[theme]
base="light"
primaryColor="#1f77b4"         # A clean finance blue
backgroundColor="#ffffff"      # White background
secondaryBackgroundColor="#f5f7fa"  # Soft grey panels
textColor="#1a1a1a"            # Almost-black text
font="sans serif"              # Clean default font
