[theme]
base = "dark"
primaryColor = "#1f6fba"                # Clean blue (buttons, highlights)
backgroundColor = "#0d1117"             # Deep navy background
secondaryBackgroundColor = "#1a2332"    # Blue-grey cards/panels
textColor = "#e6e6e6"                   # Light grey text
font = "sans serif"
